server:
  port: 8113
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8000/auth/realms/ems
        registration:
          keycloak:
            client-id: admin-cli
            authorization-grant-type: password
logging:
  level:
    root: warn
    com.example.service3: debug